# Generated by Django 4.2.17 on 2025-01-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True, verbose_name='درباره کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name=' آدرس '),
        ),
        migrations.AddField(
            model_name='user',
            name='admission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ادمین'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile', verbose_name='آواتار'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=' تاریخ تولد '),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'مرد'), ('Female', 'زن')], default='-----', max_length=13, null=True, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' شغل'),
        ),
        migrations.AddField(
            model_name='user',
            name='legendry_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=' کد ملی '),
        ),
        migrations.AddField(
            model_name='user',
            name='post_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('customer', 'مشتری'), ('vendor', 'فروشنده')], default='customer', max_length=13, null=True, verbose_name='وضعیت کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن'),
        ),
    ]
