# Generated by Django 4.2.18 on 2025-02-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_about_user_user_address_user_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_active_code',
        ),
    ]
