# Generated by Django 4.2.7 on 2023-12-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_index=True, max_length=500, verbose_name='توضیحات اصلی'),
        ),
    ]
