# Generated by Django 4.2.7 on 2023-12-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_producttag_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name=' نام برند ')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': ' برند ',
                'verbose_name_plural': 'برند ها ',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_brand', verbose_name=' برند '),
        ),
    ]
