# Generated by Django 4.2.6 on 2024-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_brand',
            name='url_title',
            field=models.CharField(db_index=True, default='url_title', max_length=300, verbose_name=' نام در url '),
            preserve_default=False,
        ),
    ]
