# Generated by Django 5.0.2 on 2024-11-30 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='تعداد موجودی')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت خرید')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'انبارداری',
                'verbose_name_plural': 'انبارداری',
            },
        ),
    ]
