# Generated by Django 5.0.2 on 2024-11-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'ورود'), ('out', 'خروج')], max_length=3, verbose_name='نوع عملیات')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='هزینه کل')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان عملیات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
        ),
    ]
