# Generated by Django 5.0.2 on 2024-11-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_stocktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
    ]
