# Generated by Django 5.0.2 on 2024-11-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_inventory_stock_quantity_inventory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='total_cost',
        ),
    ]
