# Generated by Django 5.0.2 on 2024-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_stocktransaction_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت خرید'),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
