# Generated by Django 4.2.18 on 2025-02-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_color_size_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(help_text='برای رنگ\u200cهای متداول در فروشگاه لباس می\u200cتوانید از این کدها استفاده کنید:<br>#000000 (مشکی), #FFFFFF (سفید), #808080 (خاکستری), #C0C0C0 (نقره\u200cای),<br>#FF0000 (قرمز), #800000 (زرشکی), #FFA500 (نارنجی), #FFFF00 (زرد),<br>#008000 (سبز), #00FFFF (فیروزه\u200cای), #0000FF (آبی), #800080 (بنفش), #FFC0CB (صورتی)', max_length=7, unique=True, verbose_name='کد رنگ (HEX)'),
        ),
    ]
