# Generated by Django 4.2.18 on 2025-02-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='exchange_days',
            field=models.PositiveIntegerField(default=10, verbose_name='مدت تعویض (روز)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.IntegerField(default=0, verbose_name='هزینه ارسال'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد ماه گارانتی'),
        ),
    ]
