# Generated by Django 4.2.18 on 2025-02-08 15:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_discount_percent_product_exchange_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='درصد تخفیف'),
        ),
    ]
