# Generated by Django 4.2.18 on 2025-02-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان ابر دسته\u200cبندی')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان ابر دسته\u200cبندی در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'ابر دسته\u200cبندی',
                'verbose_name_plural': 'ابر دسته\u200cبندی ها',
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.supercategory', verbose_name='ابر دسته\u200cبندی'),
        ),
    ]
