# Generated by Django 4.2.18 on 2025-02-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مشخصه')),
            ],
            options={
                'verbose_name': 'عنوان مشخصه',
                'verbose_name_plural': 'عناوین مشخصه',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار مشخصه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.product', verbose_name='محصول')),
                ('specification_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.specificationtitle', verbose_name='عنوان مشخصه')),
            ],
            options={
                'verbose_name': 'مشخصه محصول',
                'verbose_name_plural': 'مشخصات محصولات',
                'unique_together': {('product', 'specification_title')},
            },
        ),
    ]
