# Generated by Django 4.2.18 on 2025-03-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'ورایانت محصول',
                'verbose_name_plural': 'ورایانت\u200cهای محصول',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
