# Generated by Django 5.1.7 on 2025-03-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_product_colors_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'verbose_name': 'انبار محصولات', 'verbose_name_plural': 'انبار محصولات'},
        ),
    ]
