# Generated by Django 5.1.7 on 2025-03-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_stocktransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/supercategory', verbose_name='تصویر محصول'),
        ),
    ]
