# Generated by Django 4.2.7 on 2023-12-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=' فعال / غیرفعال'),
        ),
    ]
