# Generated by Django 4.2.7 on 2023-12-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name=' عنوان ')),
                ('email', models.EmailField(max_length=300, verbose_name=' ایمیل ')),
                ('full_name', models.CharField(max_length=300, verbose_name=' نام و نام خانوادگی ')),
                ('message', models.TextField(max_length=300, verbose_name=' متن تماس با ما ')),
                ('is_read_by_admin', models.BooleanField(verbose_name=' مشاهده شده توسط ادمین ')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name=' تاریح ایجاد ')),
                ('response', models.TextField(blank=True, max_length=300, null=True, verbose_name=' متن پاسخ تماس با ما ')),
            ],
            options={
                'verbose_name': ' نماس با ما ',
                'verbose_name_plural': ' لیست تماس با ما ',
            },
        ),
    ]
