# Generated by Django 4.2.7 on 2023-12-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
