# Generated by Django 4.2.7 on 2023-12-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_full_name_contact_us_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
