# Generated by Django 4.2.7 on 2023-12-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_fullname_contact_us_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='is_read_by_admin',
            field=models.BooleanField(default=False, verbose_name=' مشاهده شده توسط ادمین '),
        ),
    ]
