# Generated by Django 4.2.7 on 2024-01-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlecategory_parent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecategory',
            table=None,
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان  مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, verbose_name='عنوان در url')),
                ('image', models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')),
                ('short_description', models.TextField(verbose_name=' توضیحات کوتاه')),
                ('is_active', models.BooleanField(default=True, verbose_name=' فعال / غیر فعال')),
                ('selected_categories', models.ManyToManyField(to='article.articlecategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': ' مقاله',
                'verbose_name_plural': ' مقالات ',
            },
        ),
    ]
