# Generated by Django 4.2.7 on 2024-01-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_articlecategory_table_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(null=True, verbose_name='متن مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان مقاله'),
        ),
    ]
