# Generated by Django 4.2.6 on 2024-01-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': ' نظر مقاله', 'verbose_name_plural': ' نظرات مقاله '},
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
