# Generated by Django 4.2.6 on 2024-01-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_articlecomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ ثبت'),
        ),
    ]
