# Generated by Django 4.2.18 on 2025-03-16 20:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_article_options_article_dislikes_article_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='متن مقاله'),
        ),
    ]
