# Generated by Django 4.2.18 on 2025-03-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_product_colors_remove_product_sizes_and_more'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='Cart.CartDetail', to='product.product', verbose_name='محصولات'),
        ),
    ]
