# Generated by Django 4.2.18 on 2025-03-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
