# Generated by Django 4.2.18 on 2025-03-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_remove_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.IntegerField(blank=True, default=0, help_text='قیمت کل سبد خرید، محاسبه شده بر اساس قیمت هر آیتم ضرب در تعداد', null=True, verbose_name='قیمت کل'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.IntegerField(default=0, help_text='قیمت واحد ثبت شده هنگام خرید', verbose_name='قیمت واحد'),
        ),
    ]
