# Generated by Django 4.2.18 on 2025-03-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_cart_final_price_cartitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
