# Generated by Django 4.2.18 on 2025-03-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_remove_cart_final_price_remove_cartitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.IntegerField(blank=True, help_text='قیمت کل سبد خرید، محاسبه شده بر اساس قیمت هر آیتم ضرب در تعداد', null=True, verbose_name='قیمت کل'),
        ),
    ]
