# Generated by Django 4.2.18 on 2025-03-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_cart_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
    ]
