# Generated by Django 4.2.18 on 2025-03-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_remove_cart_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.IntegerField(default=0, verbose_name='قیمت کل سفارش'),
        ),
    ]
