# Generated by Django 4.2.18 on 2025-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_cart_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.PositiveIntegerField(default=1, verbose_name='قیمت واحد'),
        ),
    ]
