# Generated by Django 4.2.18 on 2025-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0010_cartitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت واحد'),
        ),
    ]
