# Generated by Django 4.2.18 on 2025-03-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0011_alter_cartitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
    ]
