# Generated by Django 4.2.18 on 2025-03-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0012_remove_cart_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
