# Generated by Django 4.2.18 on 2025-03-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0014_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.IntegerField(blank=True, help_text='قیمت کل سبد خرید، محاسبه شده بر اساس قیمت هر آیتم ضرب در تعداد', null=True, verbose_name='قیمت کل'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.IntegerField(default=0, help_text='قیمت واحد ثبت شده هنگام خرید', verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='نهایی شده / نشده'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Cart.cart', verbose_name='سبد خرید'),
        ),
    ]
