# Generated by Django 4.2.18 on 2025-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0015_cart_final_price_cartitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('نامشخص', 'نامشخص'), ('در حال پردازش', 'در حال پردازش'), ('در حال آماده سازی محصولات', 'در حال آماده سازی محصولات'), ('در حال ارسال به دست شما', 'در حال ارسال به دست شما'), ('به شهر شما رسیدیم', 'به شهر شما رسیدیم')], default='نامشخص', max_length=50, verbose_name='وضعیت سفارش'),
        ),
    ]
