# Generated by Django 4.2.18 on 2025-03-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0016_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='final_price',
        ),
    ]
