# Generated by Django 5.1.7 on 2025-03-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteitem',
            options={'verbose_name': 'آیتم علاقه\u200cمندی', 'verbose_name_plural': 'آیتم\u200cهای علاقه\u200cمندی'},
        ),
        migrations.AlterModelOptions(
            name='favoritelist',
            options={'verbose_name': 'لیست علاقه\u200cمندی', 'verbose_name_plural': 'لیست\u200cهای علاقه\u200cمندی'},
        ),
    ]
